<?php
use Center\Functions\MemberFunctions;

    if (isset($this->member_row))
        $this->headTitle()->prepend($this->member_row["name"].' '.$this->member_row["surname"].' : : ');

?>

<div class="notification-area">
    <?php
        if ($this->document_deleted) {
            echo '<p class="top-notification top-success">Wybrany dokument został usunięty.</p>';
        }

        if ($this->member_deleted) {
            echo '<p class="top-notification top-success">Wybrany profil został usunięty.</p>';
        }
        
        if ($this->account_clear) {
            echo '<p class="top-notification top-success">Wyczyszczono twoje centrum zdrowia.</p>';
        }
    ?>
</div>

<div class="page-header">
  <h2>Centrum <small>Zarządzaj</small></h2>
</div>

<div id="center_dashboard">
    <div id="left_bar">
        <h4>Menu</h4>
        <a class="circle-link center-link <?php if ($this->url == '/center') echo 'active ' ;?>" href="/center"><span style="font-size:45px;color:grey" class="glyphicon glyphicon-flag"></span><span class="text">Statystyki</span></a>
<?php
        $count_statistic = array('k' => 0, 'm' => 0);
        foreach($this->members as $member) {
            if ($member->sex == 'k') {
                $count_statistic['k'] = $count_statistic['k'] + 1;
            } else if ($member->sex == 'm') {
                $count_statistic['m'] = $count_statistic['m'] + 1;
            }
            
            if ($this->member_id == $member->id) {
                $active_member = 'active ';
            }
            else {
                $active_member = '';
            }
            
            $avatar = MemberFunctions::getAvatar($member->id);
            if ($avatar != false) {
                $avatar_img = '<img src="'.$avatar.'" class="mini-avatar" style="display:none" />';
            } else {
                $avatar_img = '<img src="/img/user-avatar.png" class="mini-avatar" />';
            }
            echo '<a id="mem_'.$member->id.'" class="circle-link member-link '.$active_member.'" href="/center/index/'.$member->id.'">'.$avatar_img.$member->name.'</a>';
        }
        
        if (count($this->members))
            $tooltip_show = 'display:none;';
        else
            $tooltip_show = '';
?>
        <hr />
        <a class="add-link" href="/center/member/create"><span style="font-size:20px;color:lightgrey" class="glyphicon glyphicon-plus"></span><span style="<?=$tooltip_show?>;" class="tooltip-right tooltip-add-member" data-tooltip="Kliknij w plus!"></span><span class="text">Dodaj osobę</span></a>
    </div>
    
    <div id="right_area">
<?php
        if ($this->member_id) {
?>
            <ul class="nav nav-tabs" style="margin-bottom:20px">
                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        Opcje <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header"><span class="glyphicon glyphicon-plus"></span> Dodaj</li>
                        <li role="presentation">
                            <a href="/center/document/add-document/<?=$this->member_row['id']?>">Dokument</a>
                        </li>
                        <!--<li role="presentation">
                            <a href="/center/member/profile-edit/<?=$this->member_row['id']?>">Przypomnienie</a>
                        </li>-->
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header"><span class="glyphicon glyphicon-edit"></span> Edytuj</li>
                        <li role="presentation">
                            <a href="/center/member/profile-edit/<?=$this->member_row['id']?>/illness">Choroby</a>
                        </li>
                        <li role="presentation">
                            <a href="/center/member/profile-edit/<?=$this->member_row['id']?>">Dane osobowe</a>
                        </li>
                        <li role="separator" class="divider"></li>
                    </ul>
                </li>
                <li class="<?php if ($this->context == 'show') echo 'active ' ?>" role="presentation">
                    <a href="/center/index/<?=$this->member_row['id']?>/show">Profil</a>
                </li>
                <li class="<?php if ($this->context == 'docs') echo 'active ' ?>" role="presentation">
                    <a href="/center/index/<?=$this->member_row['id']?>/docs">Dokumenty</a>
                </li>
            </ul>
        
<?php
            switch($this->context) {
                case 'show':
?>
                    <div class="col-md-3">
                        <div>
                            <div class="panel panel-default">
                                <div class="panel-heading">Informacje<a href="/center/member/profile-edit/<?=$this->member_row['id']?>" style="float:right;"><span style="color:#9faab7;font-size:18px;" class="glyphicon glyphicon-cog"></span></a></div>
                                <table class="table chat-session-info">
                                    <tr>
                                        <td><strong>Imię i nazwisko:</strong> <?=$this->member_row['name'].' '.$this->member_row['surname']?></td>
                                    </tr>
                                    <tr>
                                        <td><strong>Data urodzenia:</strong> <?=$this->date_time->generateDateString($this->member_row['birth']); ?></td>
                                    </tr>
                                    <tr>
                                        <td style="background-color:white;text-align:center"><?=$this->date_time->generateHumanDevelopString($this->date_time->getDaysDiff($this->member_row['birth'], date("Y-m-d")), $this->member_row['sex'])?></td>
                                    </tr>
                                    <tr>
                                        <td><strong>Wiek:</strong> <?=$this->date_time->generateAgeString($this->member_row['birth']); ?></td>
                                    </tr>
                                    <tr>
                                        <td><strong>Wzrost:</strong> <?=$this->member_row['growth']; ?> cm</td>
                                    </tr>
                                    <tr>
                                        <td><strong>Waga:</strong> <?=$this->member_row['weight']; ?> kg</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <div>
                            <div class="panel panel-default">
                                <div class="panel-heading">Zarządzanie<span style="color:#9faab7;font-size:18px;float:right;" class="glyphicon glyphicon-wrench"></span></div>
                                    <table class="table chat-session-info">
                                        <tr>
                                            <td>                        
                                                <form style="min-width:180px;" class="form-horizontal" action="/center" method="POST">
                                                    <a style="margin-right:10px;" href="<?php echo '/center/member/profile-edit/'.$this->member_row['id']; ?>" class="btn btn-primary" role="button"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edytuj</a>
                                                    <input type="hidden" name="member-id" value="<?=$this->member_row['id']?>" />
                                                    <button onclick="return confirm('Czy na pewno chcesz usunąć profil tej osoby?');" type="submit" name="delete-member" class="btn btn-warning">
                                                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Usuń
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div>
                            <div class="panel panel-default">
                                <div class="panel-heading">Choroby<a href="/center/member/profile-edit/<?=$this->member_row['id']?>/illness" style="float:right;"><span style="color:#9faab7;font-size:18px;" class="glyphicon glyphicon-cog"></span></a></div>
                                <?php if (isset($this->member_illness["illnesses"]) && count($this->member_illness["illnesses"])) { ?>
                                <table class="table chat-session-info">
                                    <?php
                                    echo '<tr><td style="padding-left:20px;">';
                                    foreach ($this->member_illness["illnesses"] as $key => $illness) {
                                        echo '<li style="padding:3px;">'.$illness[1].'</li>';
                                    }
                                    echo '</td></tr>';
                                    //echo '<tr><td style="font-weight:bold;font-style:italic;text-align:center;background-color:white">Życzymy powrotu do zdrowia!</td></tr>';
                                    ?>
                                </table>
                                <?php } else {
                                    echo '<p style="text-align:center;font-style:italic;margin-top:10px;">Nie przypisano dolegliwości do tej osoby...<br /><a style="margin-top:10px;" role="button" class="btn btn-sm btn-info" href="/center/member/profile-edit/'.$this->member_row['id'].'/illness">Wybierz teraz!</a></p>';
                                }
                                ?>
                            </div>
                        </div>
                        <div>
                            <div class="panel panel-default">
                                <div class="panel-heading">Dokumentacja medyczna<a href="/center/index/<?=$this->member_row['id']?>/docs" style="float:right;"><span style="color:#9faab7;font-size:18px;" class="glyphicon glyphicon-th-list"></span></a></div>
                                <?php if (!count($this->member_documents)) {
                                    echo '<p style="text-align:center;font-style:italic;margin-top:10px;">Osoba nie posiada dokumentacji medycznej...<br /><a style="margin-top:10px;" role="button" class="btn btn-sm btn-success" href="/center/document/add-document/'.$this->member_row['id'].'">Dodaj dokument!</a></p>';
                                } else {
                                ?>
                                    <table class="table chat-session-info">
                                        <tr>
                                            <td><strong>Liczba pozycji:</strong> <?=count($this->member_documents)?></td>
                                        </tr>
                                    </table>
                                <?php
                                }
                                ?>
                            </div>
                        </div>
                    </div>
<?php
                break;
                case 'docs':
                    $this->headTitle()->prepend('Dokumenty : : ');
                    $i = 0;
                    if (count($this->member_documents)) {
                        foreach ($this->member_documents as $document) {
                            echo '<div class="document-box">';
                                $this->date_time->parseObject($document->testing_date);
                                if ($i != 0) echo '<hr />';
                                if ($this->date_time->year != $this->prev_year) {
                                    $this->prev_year = $this->date_time->year;
                                    $this->prev_month = $this->date_time->month_normal;
                                    echo '<div style="clear:both">';
                                        echo '<div style="border:none;margin:0;" class="page-header">';
                                          echo '<h3 style="margin-left:20px;">'.$this->prev_year.'<br /><small>'.ucfirst($this->prev_month).'</small></h3>';
                                        echo '</div>';
                                    echo '</div>';

                                }

                                if ($this->date_time->month_normal != $this->prev_month) {
                                    $this->prev_month = $this->date_time->month_normal;

                                    echo '<div style="clear:both">';
                                        echo '<div style="border:none;margin:0;" class="page-header">';
                                          echo '<h3 style="margin-left:20px;"><small>'.ucfirst($this->prev_month).'</small></h3>';
                                        echo '</div>';
                                    echo '</div>';

                                }

        ?>
                                <article>
                                    <div style="margin-left:50px;" class="">
                                        <p style="margin-left:30px;"></p>
                                        <h4 style="margin-bottom:0"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> <?=$this->date_time->day?> - <a class="" href="/center/document/add-files/<?=$document->id?>/<?=$this->member_row['id']?>"><?=$document->document_type_name?></a>
                                            <?php if ($document->document_specialization_name != '') echo ' - '.$document->document_specialization_name; ?>
                                        </h4>
                                        <?php if ($document->description != '') {
                                            echo '<p style="margin:0 0 30px 0;color:grey;"><span style="color:grey" class="glyphicon glyphicon-pencil" aria-hidden="true"></span> '.$document->description.'</p>';
                                        }      
                                        ?>
                                    </div>
                                </article>
        <?php                   $i++;
                            echo '</div>';
                        }
                    } else {
                        echo '<p style="margin-left:30px;font-style:italic">Nie dodano jeszcze żadnych dokumentów...<br /><a style="margin-top:10px;" role="button" class="btn btn-sm btn-success" href="/center/document/add-document/'.$this->member_row['id'].'">Dodaj pierwszy dokument!</a></p>';
                    }
                break;
            }
?>

<?php
        }else {
?>
            <ul class="nav nav-tabs" style="margin-bottom:20px">
                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        Opcje <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header"><span class="glyphicon glyphicon-home"></span> Konto</li>
                        <li role="presentation">
                            <a style="padding:0;" href="#"><form style="display:inline-block;" class="form-horizontal" action="/center" method="POST">
                                <button style="text-decoration:none;color:black;width:170px;text-align:left;padding-left:20px;" role="link" onclick="return confirm('Czy na pewno chcesz usunąć dodane osoby wraz z danymi?');" type="submit" name="clear-account" class="btn btn-link">
                                    Wyczyść
                                </button>
                            </form></a>

                        </li>
                        <li role="presentation">
                            <a style="padding:0;" href="#"><form style="display:inline-block" class="form-horizontal" action="/" method="POST">
                                <button style="text-decoration:none;color:black;min-width:170px;text-align:left;padding-left:20px;" role="link" onclick="return confirm('Czy na pewno chcesz usunąć swoje konto w naszym serwisie?');" type="submit" name="delete-account" class="btn btn-link">
                                    Usuń
                                </button>
                            </form></a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header"><span class="glyphicon glyphicon-plus"></span> Dodaj</li>
                        <li role="presentation">
                            <a href="/center/member/create<?=$this->member_row['id']?>">Osobę</a>
                        </li>
                    </ul>
                </li>
                <li class="active" role="presentation">
                    <a href="/center">Statystyki</a>
                </li>
            </ul>
<?php
            if (count($this->members)) {
?>
                <div class="col-md-3">
                    <div>
                        <div class="panel panel-default">
                            <div class="panel-heading">Obserwowane osoby<span style="color:#9faab7;font-size:18px;float:right" class="glyphicon glyphicon-user"></span></div>
                                <table class="table chat-session-info">
                                    <tr>
                                        <td><strong>Liczba osób:</strong> <?=count($this->members)?></td>
                                    </tr>
                                    <tr>
                                        <td style="padding-left:30px">kobiety: <?=$count_statistic['k']?></td>
                                    </tr>
                                    <tr>
                                        <td style="padding-left:30px">mężczyźni: <?=$count_statistic['m']?></td>
                                    </tr>
                                </table>
                        </div>
                    </div>
                    <div>
                        <div class="panel panel-default">
                            <div class="panel-heading">Dokumentacja medyczna<span style="color:#9faab7;font-size:18px;float:right" class="glyphicon glyphicon-briefcase"></span></div>
                                <table class="table chat-session-info">
                                    <tr>
                                        <td><strong>Dodane dokumenty:</strong> <?=$this->all_documents_count?></td>
                                    </tr>
                                    <tr>
                                        <td style="padding-left:30px">przesłane pliki: <?=$this->all_files_count['files_count']?></td>
                                    </tr>
                                    <tr>
                                        <td style="padding-left:30px">całkowity rozmiar: <?=$this->all_files_count['files_size']?></td>
                                    </tr>
                                </table>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div>
                        <div class="panel panel-default">
                            <div class="panel-heading">Zarządzanie kontem<span style="color:#9faab7;font-size:18px;float:right" class="glyphicon glyphicon-wrench"></span></div>
                                <table class="table chat-session-info">
                                    <tr>
                                        <td>
                                            <form style="display:inline-block;margin-right:10px;" class="form-horizontal" action="/center" method="POST">
                                                <button onclick="return confirm('Czy na pewno chcesz usunąć dodane osoby wraz z danymi?');" type="submit" name="clear-account" class="btn btn-warning">
                                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Wyczyść
                                                </button>
                                            </form>
                                            <form style="display:inline-block" class="form-horizontal" action="/" method="POST">
                                                <button onclick="return confirm('Czy na pewno chcesz usunąć swoje konto w naszym serwisie?');" type="submit" name="delete-account" class="btn btn-danger">
                                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Usuń
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                </table>
                        </div>
                    </div>
                </div>
<?php
            } else {
                echo '<div style="margin:20px 0 0 20px;">';
                echo '<p style="font-size:16px"><span style="color:grey" class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> Dodaj siebie i członków swojej rodziny do obserwacji!</p>';
                echo '<p style="margin-left:30px;font-style:italic">Tutaj dostępne będą statystyki...<br /></p>';
                echo '</div>';
            }

        }
?>
    </div>
</div>