<?php echo $this->doctype(); ?>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <?php 
            $activeElement = $this->navigation('Zend\Navigation\default')->findOneBy('active', 1);
            echo $this->headTitle($activeElement.' . : : Domowe Centrum Zdrowia');
        ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) 
                ?>
                        

        <!-- Scripts -->
        <?php echo $this->headScript()
                
        ; ?>

    </head>
    <body>
        <script>
            document.location.href="/";
        </script>
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img style="height:27px;" src="<?php echo $this->basePath('img/dc-z-logo.png') ?>" alt="dc-z.pl"/></a>
                </div>
                <div class="collapse navbar-collapse">

                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <noscript>
                <?php
                if ($this->url() != '/noscript') {
                    echo '<meta http-equiv="refresh" content="0;url=/noscript">';
                }
                ?>
            </noscript>
            <?php echo $this->content; ?>
            
            <hr>


            <footer>
                <p>
                    &copy; 2015 <!-- - --> <?php /*echo date('Y')*/ ?> Miłosz Szewczyk. <?php echo $this->translate('All rights reserved.') ?>
                </p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
        <div class="my-bottom-breadcrumbs" style="border-radius:0 !important;">
            <div>Tutaj jesteś: </div>
            <?php
                echo $this->navigation('Zend\Navigation\Default')
                      ->breadcrumbs()
                      ->setMinDepth(0)
                      ->setPartial('partial/breadcrumb.phtml');
            ?>
            <!--<div style="display:inline-block;float:right;margin-right:10px;">
                <a href="/users/login"><span style="font-size:31px;" class="glyphicon glyphicon-log-in" aria-hidden="true"></a>
            </div>-->
        </div>
    </body>
</html>
