<div class="page-header">
  <h2>Zarządzanie <small>Panel</small></h2>
</div>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> Lista zasobów</div>

    <table class="table table-responsive">
    <tr>
        <td><a href="/admin/blog" class="btn btn-default btn-group-justified" role="button"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Wpisy bloga</a></td>
    </tr>
    <tr>
        <td><a href="/admin/taxonomies" class="btn btn-default btn-group-justified" role="button"><span class="glyphicon glyphicon-tags" aria-hidden="true"></span> Taksonomie</a></td>
    </tr>
    <tr>
        <td><a href="/admin/user-manager" class="btn btn-default btn-group-justified" role="button"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Użytkownicy systemu</a></td>
    </tr>
    </table>
</div>

