<div class="home_background">
    <div class="home_background_content">
        <h1>Zdrowie rodziny w Twoich rękach</h1>
        <p>Domowe Centrum Zdrowia to bezpłatna aplikacja internetowa, która pomoże Ci zadbać o zdrowie najbliższych.</p>
        <a style="font-weight:bold;font-size:16px;width:340px;margin-top:40px;" href="/users/register" role="button" class="btn btn-success">Zarejestruj się za darmo</a>
    </div>
</div>
<div class="notification-area">

</div>
<div class="row container home_margin_set">

    <div class="home-page-header" style="display:none;margin-top:30px;text-align:center;">
        <p style="font-size:20px;"><span class="glyphicon glyphicon-ok-circle"></span> Zadbaj o zdrowie najbliższych!<br /><small style="color:grey;">Darmowa aplikacja internetowa...</small></p>
    </div>

    <div class="start_info">
        <div style="margin:0 auto;max-width:900px;">
            <div class="col-md-5">
                <div class="panel panel-success">
                  <div class="panel-heading">Jak zacząć?</div>
                  <div class="panel-body">
                      <ul>
                          <li>Zarejestruj się</li>
                          <li>Dodaj osoby do obserwacji</li>
                          <li>Uzupełnij dane</li>
                      </ul>
                  </div>
                </div>
            </div>
            <div class="col-md-7">
                <div class="panel panel-default">
                  <div class="panel-heading">Nasza oferta!</div>
                  <div class="panel-body">
                      <ul>
                          <li>Prowadzenie dokumentacji medycznej</li>
                          <li>Tworzenie własnego bloga</li>
                          <li>Konsultacje on-line</li>
                          <!--<li>Dzienniki pomiarów</li>-->
                      </ul>
                  </div>
                </div>
            </div>
            <a style="font-weight:bold;font-size:16px;margin-top:40px;" href="/users/register" role="button" class="btn btn-success">Zarejestruj się i dodaj osoby już teraz!</a>
        </div>
    </div>
    <div class="recent-entries" style="margin-top:15px;">
        <?php
            $i = 0;
            $entries = array();
            foreach ($this->recent_entries as $entry) {
                $entries[$i] = $entry;
                $i++;
            }
        ?>
        <!--<div style="margin-right:15px;display:inline-block;width:70%;height:415px;background-image:url('<?php echo $entries[0]->photo ?>');">
            
        </div>
        <div style="display:inline-block;width:27%;">
            <div style="margin-bottom:15px;height:200px;background-image:url('<?php echo $entries[1]->photo ?>');">

            </div>
            <div style="height:200px;background-image:url('<?php echo $entries[2]->photo ?>');">

            </div>
        </div>-->
    </div>
</div>